# Generated by Django 6.0.3 on 2026-06-22 10:01

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_uuid',
            field=models.CharField(blank=True, default=shop.models.generate_uuid, editable=False, max_length=20, null=True),
        ),
    ]
