# Generated by Django 6.0.3 on 2026-06-22 10:01

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_uuid',
            field=models.CharField(default=shop.models.generate_uuid, editable=False, max_length=20, unique=True),
        ),
    ]
